#!/usr/bin/env python3
"""Assemble the TAFAT Art & Creative Studio Illustrated Guide.

Pipeline:
  1. img2pdf: each optimized infographic PNG becomes one full PDF page at its
     preserved 2:3 aspect ratio (1024x1536 px @ 150 DPI -> 491.52 x 737.28 pt).
  2. pikepdf: merge the closing page (generated by
     scripts/generate-art-guide-closing-page.ts) as the final page, set
     document metadata, and add a bookmark (outline) tree with one entry per
     page.

Requirements: python3 with img2pdf and pikepdf (pip install --break-system-packages img2pdf pikepdf).
Deterministic: same inputs => same pages and metadata.
"""
import img2pdf
import pikepdf
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)
WORK = os.environ.get("ART_GUIDE_WORK", os.path.join(REPO, "art_guide_work"))
PAGES_DIR = os.path.join(WORK, "optimized")
CLOSING = os.path.join(REPO, "public", "downloads", "art-guide-closing-page.pdf")
OUT = os.path.join(REPO, "public", "downloads", "tafat-art-creative-studio-guide.pdf")

PAGE_FILES = [
    "01_overview.png",
    "02_acrylic_paint.png",
    "03_student_vs_professional.png",
    "04_oil_paint.png",
    "05_artist_brushes.png",
    "06_canvas.png",
    "07_easels.png",
    "08_colour_theory.png",
    "09_studio_setup.png",
    "10_advanced_colour_mix_ideas.png",
    "11_advanced_colour_mixing_2.png",
    "12_before_you_buy.png",
    "13_how_tafat_evaluates.png",
]

BOOKMARKS = [
    "Cover & Overview",
    "Acrylic Paint",
    "Student vs Professional Paint",
    "Oil Paint",
    "Artist Brushes",
    "Canvas",
    "Easels",
    "Colour Theory",
    "Studio Setup",
    "Advanced Colour Mix Ideas",
    "Advanced Colour Mixing II",
    "Before You Buy Art Supplies",
    "How TAFAT Evaluates Art Products",
    "Closing Page",
]

def main() -> None:
    paths = [os.path.join(PAGES_DIR, name) for name in PAGE_FILES]
    for p in paths:
        if not os.path.exists(p):
            raise SystemExit(f"missing page image: {p}")
    layout = img2pdf.get_layout_fun(pagesize=(491.52, 737.28))  # 1024x1536 px @ 150 DPI, 2:3 preserved
    images_pdf = img2pdf.convert(paths, layout_fun=layout)
    with open(OUT, "wb") as fh:
        fh.write(images_pdf)

    with pikepdf.open(OUT, allow_overwriting_input=True) as pdf:
        with pikepdf.open(CLOSING) as closing:
            pdf.pages.append(closing.pages[0])
        assert len(pdf.pages) == len(PAGE_FILES) + 1, f"expected 14 pages, got {len(pdf.pages)}"

        try:
            with pdf.open_outline() as outline:
                for i, title in enumerate(BOOKMARKS):
                    outline.root.append(
                        pikepdf.OutlineItem(title, pdf.pages[i], color=pikepdf.Array([0.34, 0.46, 0.36]))
                    )
        except Exception as exc:  # bookmarks are best-effort; keep metadata
            print(f"warning: outline failed ({exc}); continuing without bookmarks")

        with pdf.open_metadata() as meta:
            meta["dc:title"] = "TAFAT Art & Creative Studio Illustrated Guide"
            meta["dc:description"] = (
                "TAFAT's illustrated evidence guides to artist materials and creative practice: "
                "acrylic paint, student vs professional paint, oil paint, artist brushes, canvas, easels, "
                "colour theory, studio setup, advanced colour mixing, buying art supplies, and how TAFAT "
                "evaluates art products."
            )
            meta["dc:creator"] = ["TAFAT"]
            meta["dc:publisher"] = "TAFAT"
            meta["pdf:Keywords"] = "TAFAT, art, creative studio, artist materials, colour theory, oil paint, acrylic, canvas, easels, brushes, buying guide"
            meta["pdf:Producer"] = "TAFAT (img2pdf + pikepdf)"
            meta["xmp:CreatorTool"] = "TAFAT guide pipeline"

        pdf.save(OUT)
        print(f"wrote {OUT}: {os.path.getsize(OUT)} bytes, {len(pdf.pages)} pages")

if __name__ == "__main__":
    main()
